###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID vlsi.seas.gwu.edu)
#  Generated on:      Thu Apr 30 12:06:24 2026
#  Design:            mips
#  Command:           saveFPlan ../floorplan/mips_floorplan.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 578.4000 540.0000
IO Box: 0.0000 0.0000 578.4000 540.0000
Core Box: 16.8000 15.0000 561.6000 525.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 16.8000 15.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_1 core 16.8000 45.0000 N 227 1 2.4000 0.0000
DefRow: ROW_2 core 16.8000 75.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_3 core 16.8000 105.0000 N 227 1 2.4000 0.0000
DefRow: ROW_4 core 16.8000 135.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_5 core 16.8000 165.0000 N 227 1 2.4000 0.0000
DefRow: ROW_6 core 16.8000 195.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_7 core 16.8000 225.0000 N 227 1 2.4000 0.0000
DefRow: ROW_8 core 16.8000 255.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_9 core 16.8000 285.0000 N 227 1 2.4000 0.0000
DefRow: ROW_10 core 16.8000 315.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_11 core 16.8000 345.0000 N 227 1 2.4000 0.0000
DefRow: ROW_12 core 16.8000 375.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_13 core 16.8000 405.0000 N 227 1 2.4000 0.0000
DefRow: ROW_14 core 16.8000 435.0000 FS 227 1 2.4000 0.0000
DefRow: ROW_15 core 16.8000 465.0000 N 227 1 2.4000 0.0000
DefRow: ROW_16 core 16.8000 495.0000 FS 227 1 2.4000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: X 1.2000 241 2.4000 1 3
Track: Y 1.5000 180 3.0000 1 3
Track: Y 1.5000 180 3.0000 1 2
Track: X 1.2000 241 2.4000 1 2
Track: X 1.2000 241 2.4000 1 1
Track: Y 1.5000 180 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 577.2000 2 1.2000
GCellGrid: X 1.2000 25 24.0000
GCellGrid: X 0.0000 2 1.2000
GCellGrid: Y 511.5000 2 28.5000
GCellGrid: Y 1.5000 18 30.0000
GCellGrid: Y 0.0000 2 1.5000

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd! -pwr
PhysicalNet: gnd! -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <macro_place_constraint>                                               #
#          ...                                                            #
#  </macro_place_constraint>                                              #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="mips" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x7 orient=R0>
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: mips_floorplan.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk" status="fixed" >
    <Port>
      <Pref x=0.0000 y=100.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=100.0500 urx=0.9000 ury=100.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="reset" status="fixed" >
    <Port>
      <Pref x=0.0000 y=250.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=250.0500 urx=0.9000 ury=250.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[7]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=400.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=400.0500 urx=0.9000 ury=400.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[6]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=403.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=403.0500 urx=0.9000 ury=403.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[5]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=406.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=406.0500 urx=0.9000 ury=406.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[4]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=409.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=409.0500 urx=0.9000 ury=409.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[3]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=412.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=412.0500 urx=0.9000 ury=412.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[2]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=415.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=415.0500 urx=0.9000 ury=415.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[1]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=418.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=418.0500 urx=0.9000 ury=418.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memdata[0]" status="fixed" >
    <Port>
      <Pref x=0.0000 y=421.5000 side=W width=0.9000 depth=0.9000 orientation=R270 />
      <Layer id=2 >
        <Box llx=0.0000 lly=421.0500 urx=0.9000 ury=421.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memread" status="fixed" >
    <Port>
      <Pref x=198.0000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=197.5500 lly=0.0000 urx=198.4500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="memwrite" status="fixed" >
    <Port>
      <Pref x=349.2000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=348.7500 lly=0.0000 urx=349.6500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[7]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=97.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=97.0500 urx=578.4000 ury=97.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[6]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=94.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=94.0500 urx=578.4000 ury=94.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[5]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=91.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=91.0500 urx=578.4000 ury=91.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[4]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=88.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=88.0500 urx=578.4000 ury=88.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[3]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=85.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=85.0500 urx=578.4000 ury=85.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[2]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=82.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=82.0500 urx=578.4000 ury=82.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[1]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=79.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=79.0500 urx=578.4000 ury=79.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="adr[0]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=76.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=76.0500 urx=578.4000 ury=76.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[7]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=349.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=349.0500 urx=578.4000 ury=349.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[6]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=346.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=346.0500 urx=578.4000 ury=346.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[5]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=343.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=343.0500 urx=578.4000 ury=343.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[4]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=340.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=340.0500 urx=578.4000 ury=340.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[3]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=337.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=337.0500 urx=578.4000 ury=337.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[2]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=334.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=334.0500 urx=578.4000 ury=334.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[1]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=331.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=331.0500 urx=578.4000 ury=331.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="writedata[0]" status="fixed" >
    <Port>
      <Pref x=578.4000 y=328.5000 side=E width=0.9000 depth=0.9000 orientation=R90 />
      <Layer id=2 >
        <Box llx=577.5000 lly=328.0500 urx=578.4000 ury=328.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="test_si" status="fixed" >
    <Port>
      <Pref x=102.0000 y=540.0000 side=N width=0.9000 depth=0.9000 orientation=R180 />
      <Layer id=2 >
        <Box llx=101.5500 lly=539.1000 urx=102.4500 ury=540.0000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="test_so" status="fixed" >
    <Port>
      <Pref x=106.8000 y=540.0000 side=N width=0.9000 depth=0.9000 orientation=R180 />
      <Layer id=2 >
        <Box llx=106.3500 lly=539.1000 urx=107.2500 ury=540.0000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="test_se" status="fixed" >
    <Port>
      <Pref x=104.4000 y=540.0000 side=N width=0.9000 depth=0.9000 orientation=R180 />
      <Layer id=2 >
        <Box llx=103.9500 lly=539.1000 urx=104.8500 ury=540.0000 />
      </Layer>
    </Port>
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="mips">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
