################################################################################
# atpg.tcl — Automatic Test Pattern Generation using Synopsys TetraMAX
# Tool   : Synopsys TetraMAX ATPG
# Usage  : tmax -tcl atpg.tcl | tee atpg.log
#
# Prerequisites: dft_scan.tcl must have been run first.
# This step is OPTIONAL for solo students — include if time permits.
################################################################################

################################################################################
# 1. SETUP
################################################################################

set DESIGN_NAME  "mips"
set OUTPUT_DIR   "../output"
set REPORT_DIR   "../reports"

################################################################################
# 2. READ NETLIST AND TEST PROTOCOL
################################################################################

puts "\n========== Reading scan netlist =========="

# Read the scan-inserted gate-level netlist
read_netlist $OUTPUT_DIR/${DESIGN_NAME}_scan.v -type verilog

# Read the library (same as synthesis)
# ** EDIT: set your library path **
read_netlist /path/to/your/library/typical.v -type verilog

# Build the model
run_build_model $DESIGN_NAME

# Read the test protocol (generated by DC during DFT insertion)
read_procfile $OUTPUT_DIR/${DESIGN_NAME}.spf

################################################################################
# 3. STUCK-AT FAULT ATPG
################################################################################

puts "\n========== Running stuck-at ATPG =========="

# Add all stuck-at faults
add_faults -all

# Run ATPG — det_limit controls max patterns generated
run_atpg -det_limit 2000

################################################################################
# 4. FAULT SIMULATION & COVERAGE REPORT
################################################################################

puts "\n========== Fault simulation =========="

run_simulation -measure fault_coverage

# Report fault coverage
report_faults  > $REPORT_DIR/atpg_faults.rpt
report_patterns > $REPORT_DIR/atpg_patterns.rpt
report_summaries > $REPORT_DIR/atpg_summary.rpt

puts "Target fault coverage: > 90%"
puts "ATPG reports saved to $REPORT_DIR/"

################################################################################
# 5. WRITE PATTERNS
################################################################################

# Write test patterns in WGL format (usable by most testers)
write_patterns $OUTPUT_DIR/${DESIGN_NAME}_patterns.wgl -format wgl

# Write in STIL format (alternative)
write_patterns $OUTPUT_DIR/${DESIGN_NAME}_patterns.stil -format stil

puts "Patterns written."

exit
