/*
###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID vlsi.seas.gwu.edu)
#  Generated on:      Thu Apr 30 14:57:48 2026
#  Design:            mips
#  Command:           saveNetlist netlists/mips.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP1
// Date      : Mon Apr 27 16:10:05 2026
/////////////////////////////////////////////////////////////
module mips (
	clk, 
	reset, 
	memdata, 
	memread, 
	memwrite, 
	adr, 
	writedata, 
	test_si, 
	test_so, 
	test_se);
   input clk;
   input reset;
   input [7:0] memdata;
   output memread;
   output memwrite;
   output [7:0] adr;
   output [7:0] writedata;
   input test_si;
   output test_so;
   input test_se;

   // Internal wires
   wire FE_OFN18_n182;
   wire FE_OFN17_n197;
   wire FE_OFN16_n196;
   wire FE_OFN15_n191;
   wire FE_OFN14_n189;
   wire FE_OFN13_n188;
   wire FE_OFN12_n187;
   wire FE_OFN11_n186;
   wire FE_OFN10_n185;
   wire FE_OFN9_n184;
   wire FE_OFN8_n183;
   wire FE_OFN7_n562;
   wire FE_OFN6_n410;
   wire FE_OFN5_n409;
   wire FE_OFN4_n366;
   wire FE_OFN3_n365;
   wire FE_OFN2_n310;
   wire FE_OFN1_n214;
   wire FE_OFN0_n190;
   wire dp_n20;
   wire dp_n19;
   wire dp_n18;
   wire dp_n17;
   wire dp_n16;
   wire dp_n15;
   wire dp_n14;
   wire dp_n13;
   wire dp_n12;
   wire dp_n11;
   wire dp_n10;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n42;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n69;
   wire n71;
   wire n73;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n451;
   wire n452;
   wire n453;
   wire n467;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n577;
   wire n578;
   wire n579;
   wire n580;
   wire n581;
   wire n582;
   wire n583;
   wire n584;
   wire n585;
   wire n586;
   wire n587;
   wire n588;
   wire n589;
   wire n590;
   wire n591;
   wire n592;
   wire n593;
   wire n594;
   wire n595;
   wire n596;
   wire n597;
   wire n598;
   wire n599;
   wire n600;
   wire n601;
   wire n602;
   wire n603;
   wire n604;
   wire n605;
   wire n606;
   wire [31:0] instr;
   wire [3:0] cont_nextstate;
   wire [3:0] cont_state;
   wire [7:0] dp_aluout;
   wire [7:0] dp_rd2;
   wire [7:0] dp_a;
   wire [7:0] dp_rd1;
   wire [7:0] dp_md;
   wire [7:0] dp_pc;
   wire [55:0] dp_rf_REGS;

   assign test_so = writedata[7] ;

   BUFX2 FE_OFC18_n182 (.A(n182),
	.Y(FE_OFN18_n182));
   BUFX2 FE_OFC17_n197 (.A(n197),
	.Y(FE_OFN17_n197));
   BUFX2 FE_OFC16_n196 (.A(n196),
	.Y(FE_OFN16_n196));
   BUFX2 FE_OFC15_n191 (.A(n191),
	.Y(FE_OFN15_n191));
   BUFX2 FE_OFC14_n189 (.A(n189),
	.Y(FE_OFN14_n189));
   BUFX2 FE_OFC13_n188 (.A(n188),
	.Y(FE_OFN13_n188));
   BUFX2 FE_OFC12_n187 (.A(n187),
	.Y(FE_OFN12_n187));
   BUFX2 FE_OFC11_n186 (.A(n186),
	.Y(FE_OFN11_n186));
   BUFX2 FE_OFC10_n185 (.A(n185),
	.Y(FE_OFN10_n185));
   BUFX2 FE_OFC9_n184 (.A(n184),
	.Y(FE_OFN9_n184));
   BUFX2 FE_OFC8_n183 (.A(n183),
	.Y(FE_OFN8_n183));
   BUFX2 FE_OFC7_n562 (.A(n562),
	.Y(FE_OFN7_n562));
   BUFX2 FE_OFC6_n410 (.A(n410),
	.Y(FE_OFN6_n410));
   BUFX2 FE_OFC5_n409 (.A(n409),
	.Y(FE_OFN5_n409));
   BUFX2 FE_OFC4_n366 (.A(n366),
	.Y(FE_OFN4_n366));
   BUFX2 FE_OFC3_n365 (.A(n365),
	.Y(FE_OFN3_n365));
   BUFX2 FE_OFC2_n310 (.A(n310),
	.Y(FE_OFN2_n310));
   BUFX2 FE_OFC1_n214 (.A(n214),
	.Y(FE_OFN1_n214));
   BUFX2 FE_OFC0_n190 (.A(n190),
	.Y(FE_OFN0_n190));
   DFFSR cont_state_reg_2_ (.CLK(clk),
	.D(cont_nextstate[2]),
	.Q(cont_state[2]),
	.R(n575),
	.S(1'b1));
   DFFSR cont_state_reg_1_ (.CLK(clk),
	.D(cont_nextstate[1]),
	.Q(cont_state[1]),
	.R(n575),
	.S(1'b1));
   DFFSR cont_state_reg_0_ (.CLK(clk),
	.D(cont_nextstate[0]),
	.Q(cont_state[0]),
	.R(n575),
	.S(1'b1));
   DFFSR cont_state_reg_3_ (.CLK(clk),
	.D(cont_nextstate[3]),
	.Q(cont_state[3]),
	.R(n575),
	.S(1'b1));
   INVX2 U1 (.A(n542),
	.Y(n1));
   INVX2 U2 (.A(n554),
	.Y(n2));
   INVX2 U3 (.A(n540),
	.Y(n3));
   INVX2 U4 (.A(n209),
	.Y(n4));
   INVX2 U5 (.A(n533),
	.Y(n5));
   INVX2 U6 (.A(n262),
	.Y(n6));
   INVX2 U7 (.A(n297),
	.Y(n7));
   INVX2 U8 (.A(n539),
	.Y(n8));
   INVX2 U9 (.A(n295),
	.Y(n9));
   INVX2 U10 (.A(n538),
	.Y(n10));
   INVX2 U11 (.A(n316),
	.Y(n11));
   INVX2 U12 (.A(n537),
	.Y(n12));
   INVX2 U13 (.A(n320),
	.Y(n13));
   INVX2 U14 (.A(n536),
	.Y(n14));
   INVX2 U15 (.A(n324),
	.Y(n15));
   INVX2 U16 (.A(n253),
	.Y(n16));
   INVX2 U17 (.A(n535),
	.Y(n17));
   INVX2 U18 (.A(n251),
	.Y(n18));
   INVX2 U19 (.A(n243),
	.Y(n19));
   INVX2 U20 (.A(n274),
	.Y(n20));
   INVX2 U21 (.A(n271),
	.Y(n21));
   INVX2 U22 (.A(n282),
	.Y(n22));
   INVX2 U23 (.A(n279),
	.Y(n23));
   INVX2 U24 (.A(n290),
	.Y(n24));
   INVX2 U25 (.A(n287),
	.Y(n25));
   INVX2 U26 (.A(n302),
	.Y(n26));
   INVX2 U27 (.A(n332),
	.Y(n27));
   INVX2 U28 (.A(n330),
	.Y(n28));
   INVX2 U29 (.A(n335),
	.Y(n29));
   INVX2 U30 (.A(n337),
	.Y(n30));
   INVX2 U31 (.A(n206),
	.Y(n31));
   INVX2 U32 (.A(n261),
	.Y(n32));
   INVX2 U33 (.A(n241),
	.Y(n33));
   INVX2 U34 (.A(n237),
	.Y(n34));
   INVX2 U36 (.A(n341),
	.Y(n36));
   INVX2 U42 (.A(n200),
	.Y(n42));
   INVX2 U45 (.A(n199),
	.Y(n45));
   INVX2 U46 (.A(n202),
	.Y(n46));
   INVX2 U47 (.A(n204),
	.Y(n47));
   INVX2 U48 (.A(instr[31]),
	.Y(n48));
   INVX2 U49 (.A(n544),
	.Y(n49));
   INVX2 U50 (.A(instr[26]),
	.Y(n50));
   INVX2 U51 (.A(instr[27]),
	.Y(n51));
   INVX2 U52 (.A(instr[28]),
	.Y(n52));
   INVX2 U53 (.A(instr[29]),
	.Y(n53));
   INVX2 U54 (.A(instr[30]),
	.Y(n54));
   INVX2 U55 (.A(instr[0]),
	.Y(n55));
   INVX2 U56 (.A(instr[1]),
	.Y(n56));
   INVX2 U57 (.A(instr[2]),
	.Y(n57));
   INVX2 U58 (.A(instr[3]),
	.Y(n58));
   INVX2 U59 (.A(instr[4]),
	.Y(n59));
   INVX2 U60 (.A(instr[5]),
	.Y(n60));
   INVX2 U61 (.A(dp_n20),
	.Y(n61));
   INVX2 U62 (.A(dp_n19),
	.Y(n62));
   INVX2 U63 (.A(dp_n18),
	.Y(n63));
   INVX2 U64 (.A(n354),
	.Y(n64));
   INVX2 U65 (.A(n355),
	.Y(n65));
   INVX2 U66 (.A(n356),
	.Y(n66));
   INVX2 U67 (.A(dp_n14),
	.Y(n67));
   INVX2 U69 (.A(dp_n13),
	.Y(n69));
   INVX2 U71 (.A(dp_n11),
	.Y(n71));
   INVX2 U73 (.A(dp_n10),
	.Y(n73));
   INVX2 U76 (.A(n314),
	.Y(n76));
   INVX2 U77 (.A(n328),
	.Y(n77));
   INVX2 U78 (.A(n264),
	.Y(n78));
   INVX2 U79 (.A(n246),
	.Y(n79));
   INVX2 U80 (.A(n272),
	.Y(n80));
   INVX2 U81 (.A(n280),
	.Y(n81));
   INVX2 U82 (.A(n288),
	.Y(n82));
   INVX2 U83 (.A(n303),
	.Y(n83));
   INVX2 U84 (.A(n215),
	.Y(n84));
   INVX2 U85 (.A(n344),
	.Y(n85));
   INVX2 U86 (.A(n357),
	.Y(n86));
   INVX2 U87 (.A(n556),
	.Y(n87));
   INVX2 U88 (.A(FE_OFN1_n214),
	.Y(n88));
   INVX2 U90 (.A(n359),
	.Y(memwrite));
   INVX2 U91 (.A(n353),
	.Y(n91));
   INVX2 U92 (.A(n181),
	.Y(n92));
   INVX2 U93 (.A(n553),
	.Y(n93));
   INVX2 U94 (.A(n346),
	.Y(n94));
   INVX2 U95 (.A(cont_state[2]),
	.Y(n95));
   INVX2 U96 (.A(n347),
	.Y(n96));
   INVX2 U97 (.A(cont_state[1]),
	.Y(n97));
   INVX2 U98 (.A(cont_state[0]),
	.Y(n98));
   INVX2 U99 (.A(dp_aluout[7]),
	.Y(n99));
   INVX2 U100 (.A(dp_rf_REGS[55]),
	.Y(n100));
   INVX2 U101 (.A(dp_rf_REGS[47]),
	.Y(n101));
   INVX2 U102 (.A(dp_rf_REGS[39]),
	.Y(n102));
   INVX2 U103 (.A(dp_rf_REGS[31]),
	.Y(n103));
   INVX2 U104 (.A(dp_rf_REGS[23]),
	.Y(n104));
   INVX2 U105 (.A(dp_rf_REGS[15]),
	.Y(n105));
   INVX2 U106 (.A(dp_rf_REGS[7]),
	.Y(n106));
   INVX2 U107 (.A(dp_pc[0]),
	.Y(n107));
   INVX2 U108 (.A(dp_aluout[0]),
	.Y(n108));
   INVX2 U109 (.A(dp_rf_REGS[48]),
	.Y(n109));
   INVX2 U110 (.A(dp_rf_REGS[40]),
	.Y(n110));
   INVX2 U111 (.A(dp_rf_REGS[32]),
	.Y(n111));
   INVX2 U112 (.A(dp_rf_REGS[24]),
	.Y(n112));
   INVX2 U113 (.A(dp_rf_REGS[16]),
	.Y(n113));
   INVX2 U114 (.A(dp_rf_REGS[8]),
	.Y(n114));
   INVX2 U115 (.A(dp_rf_REGS[0]),
	.Y(n115));
   INVX2 U116 (.A(dp_pc[1]),
	.Y(n116));
   INVX2 U117 (.A(dp_aluout[1]),
	.Y(n117));
   INVX2 U118 (.A(dp_rf_REGS[49]),
	.Y(n118));
   INVX2 U119 (.A(dp_rf_REGS[41]),
	.Y(n119));
   INVX2 U120 (.A(dp_rf_REGS[33]),
	.Y(n120));
   INVX2 U121 (.A(dp_rf_REGS[25]),
	.Y(n121));
   INVX2 U122 (.A(dp_rf_REGS[17]),
	.Y(n122));
   INVX2 U123 (.A(dp_rf_REGS[9]),
	.Y(n123));
   INVX2 U124 (.A(dp_rf_REGS[1]),
	.Y(n124));
   INVX2 U125 (.A(dp_pc[2]),
	.Y(n125));
   INVX2 U126 (.A(dp_aluout[2]),
	.Y(n126));
   INVX2 U127 (.A(dp_rf_REGS[50]),
	.Y(n127));
   INVX2 U128 (.A(dp_rf_REGS[42]),
	.Y(n128));
   INVX2 U129 (.A(dp_rf_REGS[34]),
	.Y(n129));
   INVX2 U130 (.A(dp_rf_REGS[26]),
	.Y(n130));
   INVX2 U131 (.A(dp_rf_REGS[18]),
	.Y(n131));
   INVX2 U132 (.A(dp_rf_REGS[10]),
	.Y(n132));
   INVX2 U133 (.A(dp_rf_REGS[2]),
	.Y(n133));
   INVX2 U134 (.A(dp_pc[3]),
	.Y(n134));
   INVX2 U135 (.A(dp_aluout[3]),
	.Y(n135));
   INVX2 U136 (.A(dp_rf_REGS[51]),
	.Y(n136));
   INVX2 U137 (.A(dp_rf_REGS[43]),
	.Y(n137));
   INVX2 U138 (.A(dp_rf_REGS[35]),
	.Y(n138));
   INVX2 U139 (.A(dp_rf_REGS[27]),
	.Y(n139));
   INVX2 U140 (.A(dp_rf_REGS[19]),
	.Y(n140));
   INVX2 U141 (.A(dp_rf_REGS[11]),
	.Y(n141));
   INVX2 U142 (.A(dp_rf_REGS[3]),
	.Y(n142));
   INVX2 U143 (.A(dp_pc[4]),
	.Y(n143));
   INVX2 U144 (.A(dp_aluout[4]),
	.Y(n144));
   INVX2 U145 (.A(dp_rf_REGS[52]),
	.Y(n145));
   INVX2 U146 (.A(dp_rf_REGS[44]),
	.Y(n146));
   INVX2 U147 (.A(dp_rf_REGS[36]),
	.Y(n147));
   INVX2 U148 (.A(dp_rf_REGS[28]),
	.Y(n148));
   INVX2 U149 (.A(dp_rf_REGS[20]),
	.Y(n149));
   INVX2 U150 (.A(dp_rf_REGS[12]),
	.Y(n150));
   INVX2 U151 (.A(dp_rf_REGS[4]),
	.Y(n151));
   INVX2 U152 (.A(dp_pc[5]),
	.Y(n152));
   INVX2 U153 (.A(dp_aluout[5]),
	.Y(n153));
   INVX2 U154 (.A(dp_rf_REGS[53]),
	.Y(n154));
   INVX2 U155 (.A(dp_rf_REGS[45]),
	.Y(n155));
   INVX2 U156 (.A(dp_rf_REGS[37]),
	.Y(n156));
   INVX2 U157 (.A(dp_rf_REGS[29]),
	.Y(n157));
   INVX2 U158 (.A(dp_rf_REGS[21]),
	.Y(n158));
   INVX2 U159 (.A(dp_rf_REGS[13]),
	.Y(n159));
   INVX2 U160 (.A(dp_rf_REGS[5]),
	.Y(n160));
   INVX2 U161 (.A(dp_pc[6]),
	.Y(n161));
   INVX2 U162 (.A(dp_aluout[6]),
	.Y(n162));
   INVX2 U163 (.A(dp_rf_REGS[54]),
	.Y(n163));
   INVX2 U164 (.A(dp_rf_REGS[46]),
	.Y(n164));
   INVX2 U165 (.A(dp_rf_REGS[38]),
	.Y(n165));
   INVX2 U166 (.A(dp_rf_REGS[30]),
	.Y(n166));
   INVX2 U167 (.A(dp_rf_REGS[22]),
	.Y(n167));
   INVX2 U168 (.A(dp_rf_REGS[14]),
	.Y(n168));
   INVX2 U169 (.A(dp_rf_REGS[6]),
	.Y(n169));
   INVX2 U170 (.A(dp_pc[7]),
	.Y(n170));
   INVX2 U180 (.A(cont_state[3]),
	.Y(n180));
   OAI22X1 U181 (.A(n181),
	.B(n567),
	.C(n92),
	.D(n50),
	.Y(n563));
   OAI22X1 U182 (.A(n606),
	.B(n109),
	.C(FE_OFN18_n182),
	.D(FE_OFN8_n183),
	.Y(n532));
   OAI22X1 U183 (.A(n605),
	.B(n110),
	.C(FE_OFN18_n182),
	.D(FE_OFN9_n184),
	.Y(n531));
   OAI22X1 U184 (.A(n604),
	.B(n111),
	.C(FE_OFN18_n182),
	.D(FE_OFN10_n185),
	.Y(n530));
   OAI22X1 U185 (.A(n603),
	.B(n112),
	.C(FE_OFN18_n182),
	.D(FE_OFN11_n186),
	.Y(n529));
   OAI22X1 U186 (.A(n602),
	.B(n113),
	.C(FE_OFN18_n182),
	.D(FE_OFN12_n187),
	.Y(n528));
   OAI22X1 U187 (.A(n601),
	.B(n114),
	.C(FE_OFN18_n182),
	.D(FE_OFN13_n188),
	.Y(n527));
   OAI22X1 U188 (.A(n600),
	.B(n115),
	.C(FE_OFN18_n182),
	.D(FE_OFN14_n189),
	.Y(n526));
   OAI22X1 U189 (.A(dp_md[0]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[0]),
	.D(n599),
	.Y(n182));
   OAI22X1 U190 (.A(n606),
	.B(n118),
	.C(FE_OFN8_n183),
	.D(FE_OFN15_n191),
	.Y(n525));
   OAI22X1 U191 (.A(n605),
	.B(n119),
	.C(FE_OFN9_n184),
	.D(FE_OFN15_n191),
	.Y(n524));
   OAI22X1 U192 (.A(n604),
	.B(n120),
	.C(FE_OFN10_n185),
	.D(FE_OFN15_n191),
	.Y(n523));
   OAI22X1 U193 (.A(n603),
	.B(n121),
	.C(FE_OFN11_n186),
	.D(FE_OFN15_n191),
	.Y(n522));
   OAI22X1 U194 (.A(n602),
	.B(n122),
	.C(FE_OFN12_n187),
	.D(FE_OFN15_n191),
	.Y(n521));
   OAI22X1 U195 (.A(n601),
	.B(n123),
	.C(FE_OFN13_n188),
	.D(FE_OFN15_n191),
	.Y(n520));
   OAI22X1 U196 (.A(n600),
	.B(n124),
	.C(FE_OFN14_n189),
	.D(FE_OFN15_n191),
	.Y(n519));
   OAI22X1 U197 (.A(dp_md[1]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[1]),
	.D(n599),
	.Y(n191));
   OAI22X1 U198 (.A(n606),
	.B(n127),
	.C(FE_OFN8_n183),
	.D(n192),
	.Y(n518));
   OAI22X1 U199 (.A(n605),
	.B(n128),
	.C(FE_OFN9_n184),
	.D(n192),
	.Y(n517));
   OAI22X1 U200 (.A(n604),
	.B(n129),
	.C(FE_OFN10_n185),
	.D(n192),
	.Y(n516));
   OAI22X1 U201 (.A(n603),
	.B(n130),
	.C(FE_OFN11_n186),
	.D(n192),
	.Y(n515));
   OAI22X1 U202 (.A(n602),
	.B(n131),
	.C(FE_OFN12_n187),
	.D(n192),
	.Y(n514));
   OAI22X1 U203 (.A(n601),
	.B(n132),
	.C(FE_OFN13_n188),
	.D(n192),
	.Y(n513));
   OAI22X1 U204 (.A(n600),
	.B(n133),
	.C(FE_OFN14_n189),
	.D(n192),
	.Y(n512));
   OAI22X1 U205 (.A(dp_md[2]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[2]),
	.D(n599),
	.Y(n192));
   OAI22X1 U206 (.A(n606),
	.B(n136),
	.C(FE_OFN8_n183),
	.D(n193),
	.Y(n511));
   OAI22X1 U207 (.A(n605),
	.B(n137),
	.C(FE_OFN9_n184),
	.D(n193),
	.Y(n510));
   OAI22X1 U208 (.A(n604),
	.B(n138),
	.C(FE_OFN10_n185),
	.D(n193),
	.Y(n509));
   OAI22X1 U209 (.A(n603),
	.B(n139),
	.C(FE_OFN11_n186),
	.D(n193),
	.Y(n508));
   OAI22X1 U210 (.A(n602),
	.B(n140),
	.C(FE_OFN12_n187),
	.D(n193),
	.Y(n507));
   OAI22X1 U211 (.A(n601),
	.B(n141),
	.C(FE_OFN13_n188),
	.D(n193),
	.Y(n506));
   OAI22X1 U212 (.A(n600),
	.B(n142),
	.C(FE_OFN14_n189),
	.D(n193),
	.Y(n505));
   OAI22X1 U213 (.A(dp_md[3]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[3]),
	.D(n599),
	.Y(n193));
   OAI22X1 U214 (.A(n606),
	.B(n145),
	.C(FE_OFN8_n183),
	.D(n194),
	.Y(n504));
   OAI22X1 U215 (.A(n605),
	.B(n146),
	.C(FE_OFN9_n184),
	.D(n194),
	.Y(n503));
   OAI22X1 U216 (.A(n604),
	.B(n147),
	.C(FE_OFN10_n185),
	.D(n194),
	.Y(n502));
   OAI22X1 U217 (.A(n603),
	.B(n148),
	.C(FE_OFN11_n186),
	.D(n194),
	.Y(n501));
   OAI22X1 U218 (.A(n602),
	.B(n149),
	.C(FE_OFN12_n187),
	.D(n194),
	.Y(n500));
   OAI22X1 U219 (.A(n601),
	.B(n150),
	.C(FE_OFN13_n188),
	.D(n194),
	.Y(n499));
   OAI22X1 U220 (.A(n600),
	.B(n151),
	.C(FE_OFN14_n189),
	.D(n194),
	.Y(n498));
   OAI22X1 U221 (.A(dp_md[4]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[4]),
	.D(n599),
	.Y(n194));
   OAI22X1 U222 (.A(n606),
	.B(n154),
	.C(FE_OFN8_n183),
	.D(n195),
	.Y(n497));
   OAI22X1 U223 (.A(n605),
	.B(n155),
	.C(FE_OFN9_n184),
	.D(n195),
	.Y(n496));
   OAI22X1 U224 (.A(n604),
	.B(n156),
	.C(FE_OFN10_n185),
	.D(n195),
	.Y(n495));
   OAI22X1 U225 (.A(n603),
	.B(n157),
	.C(FE_OFN11_n186),
	.D(n195),
	.Y(n494));
   OAI22X1 U226 (.A(n602),
	.B(n158),
	.C(FE_OFN12_n187),
	.D(n195),
	.Y(n493));
   OAI22X1 U227 (.A(n601),
	.B(n159),
	.C(FE_OFN13_n188),
	.D(n195),
	.Y(n492));
   OAI22X1 U228 (.A(n600),
	.B(n160),
	.C(FE_OFN14_n189),
	.D(n195),
	.Y(n491));
   OAI22X1 U229 (.A(dp_md[5]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[5]),
	.D(n599),
	.Y(n195));
   OAI22X1 U230 (.A(n606),
	.B(n163),
	.C(FE_OFN8_n183),
	.D(FE_OFN16_n196),
	.Y(n490));
   OAI22X1 U231 (.A(n605),
	.B(n164),
	.C(FE_OFN9_n184),
	.D(FE_OFN16_n196),
	.Y(n489));
   OAI22X1 U232 (.A(n604),
	.B(n165),
	.C(FE_OFN10_n185),
	.D(FE_OFN16_n196),
	.Y(n488));
   OAI22X1 U233 (.A(n603),
	.B(n166),
	.C(FE_OFN11_n186),
	.D(FE_OFN16_n196),
	.Y(n487));
   OAI22X1 U234 (.A(n602),
	.B(n167),
	.C(FE_OFN12_n187),
	.D(FE_OFN16_n196),
	.Y(n486));
   OAI22X1 U235 (.A(n601),
	.B(n168),
	.C(FE_OFN13_n188),
	.D(FE_OFN16_n196),
	.Y(n485));
   OAI22X1 U236 (.A(n600),
	.B(n169),
	.C(FE_OFN14_n189),
	.D(FE_OFN16_n196),
	.Y(n484));
   OAI22X1 U237 (.A(dp_md[6]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[6]),
	.D(n599),
	.Y(n196));
   OAI22X1 U238 (.A(n606),
	.B(n100),
	.C(FE_OFN8_n183),
	.D(FE_OFN17_n197),
	.Y(n483));
   NAND3X1 U239 (.A(n45),
	.B(n42),
	.C(n198),
	.Y(n183));
   OAI22X1 U240 (.A(n605),
	.B(n101),
	.C(FE_OFN9_n184),
	.D(FE_OFN17_n197),
	.Y(n482));
   NAND3X1 U241 (.A(n198),
	.B(n42),
	.C(n199),
	.Y(n184));
   OAI22X1 U242 (.A(n604),
	.B(n102),
	.C(FE_OFN10_n185),
	.D(FE_OFN17_n197),
	.Y(n481));
   NAND3X1 U243 (.A(n198),
	.B(n45),
	.C(n200),
	.Y(n185));
   OAI22X1 U244 (.A(n603),
	.B(n103),
	.C(FE_OFN11_n186),
	.D(FE_OFN17_n197),
	.Y(n480));
   NAND3X1 U245 (.A(n199),
	.B(n198),
	.C(n200),
	.Y(n186));
   AOI21X1 U246 (.A(FE_OFN0_n190),
	.B(n201),
	.C(n202),
	.Y(n198));
   OAI22X1 U247 (.A(n602),
	.B(n104),
	.C(FE_OFN12_n187),
	.D(FE_OFN17_n197),
	.Y(n479));
   NAND3X1 U248 (.A(n45),
	.B(n42),
	.C(n203),
	.Y(n187));
   OAI22X1 U249 (.A(n601),
	.B(n105),
	.C(FE_OFN13_n188),
	.D(FE_OFN17_n197),
	.Y(n478));
   NAND3X1 U250 (.A(n199),
	.B(n42),
	.C(n203),
	.Y(n188));
   OAI22X1 U251 (.A(n600),
	.B(n106),
	.C(FE_OFN14_n189),
	.D(FE_OFN17_n197),
	.Y(n477));
   OAI22X1 U252 (.A(dp_md[7]),
	.B(FE_OFN0_n190),
	.C(dp_aluout[7]),
	.D(n599),
	.Y(n197));
   NAND3X1 U253 (.A(n200),
	.B(n45),
	.C(n203),
	.Y(n189));
   AOI21X1 U254 (.A(n201),
	.B(FE_OFN0_n190),
	.C(n46),
	.Y(n203));
   AOI22X1 U255 (.A(n47),
	.B(dp_n16),
	.C(n204),
	.D(dp_n13),
	.Y(n202));
   NAND3X1 U256 (.A(cont_state[2]),
	.B(cont_state[0]),
	.C(n205),
	.Y(n190));
   NAND3X1 U257 (.A(cont_state[3]),
	.B(n93),
	.C(cont_state[1]),
	.Y(n201));
   AOI22X1 U258 (.A(n47),
	.B(dp_n18),
	.C(n204),
	.D(n590),
	.Y(n199));
   AOI22X1 U259 (.A(n47),
	.B(dp_n17),
	.C(n204),
	.D(dp_n14),
	.Y(n200));
   NAND2X1 U260 (.A(cont_state[3]),
	.B(n206),
	.Y(n204));
   OAI22X1 U261 (.A(n107),
	.B(n207),
	.C(n208),
	.D(n209),
	.Y(n476));
   AOI22X1 U262 (.A(n88),
	.B(n533),
	.C(dp_aluout[0]),
	.D(n84),
	.Y(n208));
   OAI22X1 U263 (.A(n116),
	.B(n207),
	.C(n210),
	.D(n209),
	.Y(n475));
   AOI22X1 U264 (.A(n88),
	.B(n534),
	.C(dp_aluout[1]),
	.D(n84),
	.Y(n210));
   OAI21X1 U265 (.A(n125),
	.B(n207),
	.C(n211),
	.Y(n474));
   OAI21X1 U266 (.A(n212),
	.B(n213),
	.C(n4),
	.Y(n211));
   OAI22X1 U267 (.A(n17),
	.B(FE_OFN1_n214),
	.C(n55),
	.D(n88),
	.Y(n213));
   NOR2X1 U268 (.A(n215),
	.B(n126),
	.Y(n212));
   OAI21X1 U269 (.A(n134),
	.B(n207),
	.C(n216),
	.Y(n473));
   OAI21X1 U270 (.A(n217),
	.B(n218),
	.C(n4),
	.Y(n216));
   OAI22X1 U271 (.A(n14),
	.B(FE_OFN1_n214),
	.C(n56),
	.D(n88),
	.Y(n218));
   NOR2X1 U272 (.A(n215),
	.B(n135),
	.Y(n217));
   OAI21X1 U273 (.A(n143),
	.B(n207),
	.C(n219),
	.Y(n472));
   OAI21X1 U274 (.A(n220),
	.B(n221),
	.C(n4),
	.Y(n219));
   OAI22X1 U275 (.A(n12),
	.B(FE_OFN1_n214),
	.C(n57),
	.D(n88),
	.Y(n221));
   NOR2X1 U276 (.A(n215),
	.B(n144),
	.Y(n220));
   OAI21X1 U277 (.A(n152),
	.B(n207),
	.C(n222),
	.Y(n471));
   OAI21X1 U278 (.A(n223),
	.B(n224),
	.C(n4),
	.Y(n222));
   OAI22X1 U279 (.A(n10),
	.B(FE_OFN1_n214),
	.C(n58),
	.D(n88),
	.Y(n224));
   NOR2X1 U280 (.A(n215),
	.B(n153),
	.Y(n223));
   OAI21X1 U281 (.A(n161),
	.B(n207),
	.C(n225),
	.Y(n470));
   OAI21X1 U282 (.A(n226),
	.B(n227),
	.C(n4),
	.Y(n225));
   OAI22X1 U283 (.A(n8),
	.B(FE_OFN1_n214),
	.C(n59),
	.D(n88),
	.Y(n227));
   NOR2X1 U284 (.A(n215),
	.B(n162),
	.Y(n226));
   OAI21X1 U285 (.A(n170),
	.B(n207),
	.C(n228),
	.Y(n469));
   OAI21X1 U286 (.A(n229),
	.B(n230),
	.C(n4),
	.Y(n228));
   NAND2X1 U287 (.A(n575),
	.B(n231),
	.Y(n209));
   OAI22X1 U288 (.A(n3),
	.B(FE_OFN1_n214),
	.C(n60),
	.D(n88),
	.Y(n230));
   NOR2X1 U289 (.A(n215),
	.B(n99),
	.Y(n229));
   OR2X2 U290 (.A(n231),
	.B(reset),
	.Y(n207));
   OAI21X1 U291 (.A(n232),
	.B(n233),
	.C(n234),
	.Y(n231));
   NOR2X1 U292 (.A(n94),
	.B(FE_OFN1_n214),
	.Y(n234));
   NOR2X1 U293 (.A(n235),
	.B(n180),
	.Y(n214));
   NAND3X1 U294 (.A(n84),
	.B(n5),
	.C(n236),
	.Y(n233));
   NOR2X1 U295 (.A(n535),
	.B(n534),
	.Y(n236));
   OAI21X1 U296 (.A(n79),
	.B(n237),
	.C(n238),
	.Y(n534));
   AOI22X1 U297 (.A(n239),
	.B(n240),
	.C(n241),
	.D(n242),
	.Y(n238));
   XOR2X1 U298 (.A(n243),
	.B(n244),
	.Y(n242));
   XOR2X1 U299 (.A(n79),
	.B(n28),
	.Y(n244));
   OAI21X1 U300 (.A(n79),
	.B(n245),
	.C(n237),
	.Y(n239));
   OAI21X1 U301 (.A(n247),
	.B(n33),
	.C(n248),
	.Y(n535));
   AOI22X1 U302 (.A(n249),
	.B(n35),
	.C(n34),
	.D(n250),
	.Y(n248));
   NAND2X1 U303 (.A(n77),
	.B(n18),
	.Y(n250));
   NOR2X1 U304 (.A(n77),
	.B(n18),
	.Y(n249));
   XOR2X1 U305 (.A(n252),
	.B(n253),
	.Y(n247));
   XOR2X1 U306 (.A(n254),
	.B(n77),
	.Y(n252));
   NAND3X1 U307 (.A(n255),
	.B(n256),
	.C(n257),
	.Y(n533));
   AOI22X1 U308 (.A(n258),
	.B(n6),
	.C(n241),
	.D(n259),
	.Y(n257));
   XOR2X1 U309 (.A(n29),
	.B(n260),
	.Y(n259));
   XOR2X1 U310 (.A(n261),
	.B(n78),
	.Y(n260));
   NAND3X1 U311 (.A(n263),
	.B(n264),
	.C(n35),
	.Y(n256));
   OAI21X1 U312 (.A(n263),
	.B(n264),
	.C(n34),
	.Y(n255));
   NAND3X1 U313 (.A(n265),
	.B(n10),
	.C(n266),
	.Y(n232));
   NOR2X1 U314 (.A(n537),
	.B(n536),
	.Y(n266));
   OAI21X1 U315 (.A(n267),
	.B(n33),
	.C(n268),
	.Y(n536));
   AOI22X1 U316 (.A(n269),
	.B(n35),
	.C(n34),
	.D(n270),
	.Y(n268));
   NAND2X1 U317 (.A(n80),
	.B(n21),
	.Y(n270));
   NOR2X1 U318 (.A(n80),
	.B(n21),
	.Y(n269));
   XOR2X1 U319 (.A(n273),
	.B(n274),
	.Y(n267));
   XOR2X1 U320 (.A(n272),
	.B(n15),
	.Y(n273));
   OAI21X1 U321 (.A(n275),
	.B(n33),
	.C(n276),
	.Y(n537));
   AOI22X1 U322 (.A(n277),
	.B(n35),
	.C(n34),
	.D(n278),
	.Y(n276));
   NAND2X1 U323 (.A(n81),
	.B(n23),
	.Y(n278));
   NOR2X1 U324 (.A(n81),
	.B(n23),
	.Y(n277));
   XOR2X1 U325 (.A(n281),
	.B(n282),
	.Y(n275));
   XOR2X1 U326 (.A(n280),
	.B(n13),
	.Y(n281));
   OAI21X1 U327 (.A(n283),
	.B(n33),
	.C(n284),
	.Y(n538));
   AOI22X1 U328 (.A(n285),
	.B(n35),
	.C(n34),
	.D(n286),
	.Y(n284));
   NAND2X1 U329 (.A(n82),
	.B(n25),
	.Y(n286));
   NOR2X1 U330 (.A(n82),
	.B(n25),
	.Y(n285));
   XOR2X1 U331 (.A(n289),
	.B(n290),
	.Y(n283));
   XOR2X1 U332 (.A(n288),
	.B(n11),
	.Y(n289));
   NOR2X1 U333 (.A(n540),
	.B(n539),
	.Y(n265));
   OAI21X1 U334 (.A(n291),
	.B(n33),
	.C(n292),
	.Y(n539));
   AOI22X1 U335 (.A(n293),
	.B(n35),
	.C(n34),
	.D(n294),
	.Y(n292));
   NAND2X1 U336 (.A(n76),
	.B(n9),
	.Y(n294));
   NOR2X1 U337 (.A(n76),
	.B(n9),
	.Y(n293));
   XOR2X1 U338 (.A(n296),
	.B(n297),
	.Y(n291));
   XOR2X1 U339 (.A(n298),
	.B(n76),
	.Y(n296));
   OAI21X1 U340 (.A(n262),
	.B(n33),
	.C(n299),
	.Y(n540));
   AOI22X1 U341 (.A(n300),
	.B(n35),
	.C(n34),
	.D(n301),
	.Y(n299));
   NAND2X1 U342 (.A(n83),
	.B(n26),
	.Y(n301));
   NAND2X1 U343 (.A(instr[0]),
	.B(n35),
	.Y(n237));
   NOR2X1 U344 (.A(n83),
	.B(n26),
	.Y(n300));
   NOR2X1 U345 (.A(n35),
	.B(n258),
	.Y(n241));
   NOR3X1 U346 (.A(n304),
	.B(instr[0]),
	.C(n58),
	.Y(n258));
   NAND3X1 U347 (.A(instr[2]),
	.B(n36),
	.C(n305),
	.Y(n245));
   NOR2X1 U348 (.A(instr[3]),
	.B(instr[1]),
	.Y(n305));
   XOR2X1 U349 (.A(n306),
	.B(n307),
	.Y(n262));
   XOR2X1 U350 (.A(n303),
	.B(n302),
	.Y(n307));
   OAI21X1 U351 (.A(n60),
	.B(n87),
	.C(n308),
	.Y(n302));
   AOI22X1 U352 (.A(writedata[7]),
	.B(n309),
	.C(dp_n19),
	.D(n27),
	.Y(n308));
   OAI21X1 U353 (.A(FE_OFN2_n310),
	.B(n170),
	.C(n311),
	.Y(n303));
   NAND2X1 U354 (.A(dp_a[7]),
	.B(FE_OFN2_n310),
	.Y(n311));
   XOR2X1 U355 (.A(n312),
	.B(n32),
	.Y(n306));
   OAI21X1 U356 (.A(n76),
	.B(n7),
	.C(n313),
	.Y(n312));
   OAI21X1 U357 (.A(n297),
	.B(n314),
	.C(n298),
	.Y(n313));
   OAI21X1 U358 (.A(n11),
	.B(n24),
	.C(n315),
	.Y(n298));
   OAI21X1 U359 (.A(n290),
	.B(n316),
	.C(n288),
	.Y(n315));
   OAI21X1 U360 (.A(FE_OFN2_n310),
	.B(n152),
	.C(n317),
	.Y(n288));
   NAND2X1 U361 (.A(dp_a[5]),
	.B(FE_OFN2_n310),
	.Y(n317));
   XNOR2X1 U362 (.A(n287),
	.B(n32),
	.Y(n290));
   OAI21X1 U363 (.A(n87),
	.B(n58),
	.C(n318),
	.Y(n287));
   AOI22X1 U364 (.A(writedata[5]),
	.B(n309),
	.C(n27),
	.D(instr[5]),
	.Y(n318));
   OAI21X1 U365 (.A(n13),
	.B(n22),
	.C(n319),
	.Y(n316));
   OAI21X1 U366 (.A(n282),
	.B(n320),
	.C(n280),
	.Y(n319));
   OAI21X1 U367 (.A(FE_OFN2_n310),
	.B(n143),
	.C(n321),
	.Y(n280));
   NAND2X1 U368 (.A(dp_a[4]),
	.B(FE_OFN2_n310),
	.Y(n321));
   XNOR2X1 U369 (.A(n279),
	.B(n32),
	.Y(n282));
   OAI21X1 U370 (.A(n57),
	.B(n87),
	.C(n322),
	.Y(n279));
   AOI22X1 U371 (.A(writedata[4]),
	.B(n309),
	.C(instr[4]),
	.D(n27),
	.Y(n322));
   OAI21X1 U372 (.A(n15),
	.B(n20),
	.C(n323),
	.Y(n320));
   OAI21X1 U373 (.A(n274),
	.B(n324),
	.C(n272),
	.Y(n323));
   OAI21X1 U374 (.A(FE_OFN2_n310),
	.B(n134),
	.C(n325),
	.Y(n272));
   NAND2X1 U375 (.A(dp_a[3]),
	.B(FE_OFN2_n310),
	.Y(n325));
   XNOR2X1 U376 (.A(n271),
	.B(n32),
	.Y(n274));
   OAI21X1 U377 (.A(n87),
	.B(n56),
	.C(n326),
	.Y(n271));
   AOI22X1 U378 (.A(writedata[3]),
	.B(n309),
	.C(instr[3]),
	.D(n27),
	.Y(n326));
   OAI21X1 U379 (.A(n77),
	.B(n16),
	.C(n327),
	.Y(n324));
   OAI21X1 U380 (.A(n253),
	.B(n328),
	.C(n254),
	.Y(n327));
   OAI21X1 U381 (.A(n28),
	.B(n19),
	.C(n329),
	.Y(n254));
   OAI21X1 U382 (.A(n243),
	.B(n330),
	.C(n246),
	.Y(n329));
   OAI21X1 U383 (.A(FE_OFN2_n310),
	.B(n116),
	.C(n331),
	.Y(n246));
   NAND2X1 U384 (.A(dp_a[1]),
	.B(FE_OFN2_n310),
	.Y(n331));
   XOR2X1 U385 (.A(n261),
	.B(n240),
	.Y(n243));
   OAI21X1 U386 (.A(n332),
	.B(n56),
	.C(n333),
	.Y(n240));
   NAND2X1 U387 (.A(writedata[1]),
	.B(n309),
	.Y(n333));
   OAI21X1 U388 (.A(n78),
	.B(n29),
	.C(n334),
	.Y(n330));
   OAI21X1 U389 (.A(n335),
	.B(n264),
	.C(n261),
	.Y(n334));
   XOR2X1 U390 (.A(n261),
	.B(n263),
	.Y(n335));
   OAI21X1 U391 (.A(n332),
	.B(n55),
	.C(n336),
	.Y(n263));
   OAI21X1 U392 (.A(writedata[0]),
	.B(n94),
	.C(n30),
	.Y(n336));
   OAI21X1 U393 (.A(FE_OFN2_n310),
	.B(n107),
	.C(n338),
	.Y(n264));
   NAND2X1 U394 (.A(dp_a[0]),
	.B(FE_OFN2_n310),
	.Y(n338));
   XNOR2X1 U395 (.A(n251),
	.B(n32),
	.Y(n253));
   OAI21X1 U396 (.A(n87),
	.B(n55),
	.C(n339),
	.Y(n251));
   AOI22X1 U397 (.A(writedata[2]),
	.B(n309),
	.C(n27),
	.D(instr[2]),
	.Y(n339));
   OAI21X1 U398 (.A(FE_OFN2_n310),
	.B(n125),
	.C(n340),
	.Y(n328));
   NAND2X1 U399 (.A(dp_a[2]),
	.B(FE_OFN2_n310),
	.Y(n340));
   XNOR2X1 U400 (.A(n295),
	.B(n32),
	.Y(n297));
   OAI21X1 U401 (.A(instr[0]),
	.B(n304),
	.C(n215),
	.Y(n261));
   NAND2X1 U402 (.A(cont_state[1]),
	.B(n85),
	.Y(n215));
   NAND3X1 U403 (.A(n36),
	.B(n57),
	.C(instr[1]),
	.Y(n304));
   NAND3X1 U404 (.A(n342),
	.B(n206),
	.C(n343),
	.Y(n341));
   NOR2X1 U405 (.A(n344),
	.B(n60),
	.Y(n343));
   NOR2X1 U406 (.A(instr[4]),
	.B(cont_state[1]),
	.Y(n342));
   OAI21X1 U407 (.A(n87),
	.B(n59),
	.C(n345),
	.Y(n295));
   AOI22X1 U408 (.A(writedata[6]),
	.B(n309),
	.C(dp_n20),
	.D(n27),
	.Y(n345));
   NAND2X1 U409 (.A(n337),
	.B(n87),
	.Y(n332));
   NOR2X1 U410 (.A(n337),
	.B(n94),
	.Y(n309));
   OAI21X1 U411 (.A(n347),
	.B(n95),
	.C(n348),
	.Y(n337));
   NAND3X1 U412 (.A(n85),
	.B(n97),
	.C(n31),
	.Y(n348));
   NAND3X1 U413 (.A(n349),
	.B(n48),
	.C(instr[29]),
	.Y(n206));
   OAI21X1 U414 (.A(FE_OFN2_n310),
	.B(n161),
	.C(n350),
	.Y(n314));
   NAND2X1 U415 (.A(dp_a[6]),
	.B(FE_OFN2_n310),
	.Y(n350));
   NAND2X1 U416 (.A(n351),
	.B(n344),
	.Y(n310));
   OAI22X1 U417 (.A(n181),
	.B(n573),
	.C(n92),
	.D(n48),
	.Y(n468));
   OAI22X1 U418 (.A(n181),
	.B(n569),
	.C(n92),
	.D(n51),
	.Y(n466));
   OAI22X1 U419 (.A(n181),
	.B(n579),
	.C(n92),
	.D(n52),
	.Y(n465));
   OAI22X1 U420 (.A(n181),
	.B(n581),
	.C(n92),
	.D(n53),
	.Y(n464));
   OAI22X1 U421 (.A(n181),
	.B(n571),
	.C(n92),
	.D(n54),
	.Y(n463));
   NAND2X1 U422 (.A(n96),
	.B(n93),
	.Y(n181));
   OAI22X1 U423 (.A(n564),
	.B(n55),
	.C(n592),
	.D(n577),
	.Y(n462));
   OAI22X1 U424 (.A(n564),
	.B(n56),
	.C(n592),
	.D(n565),
	.Y(n461));
   OAI22X1 U425 (.A(n564),
	.B(n57),
	.C(n567),
	.D(n592),
	.Y(n460));
   OAI22X1 U426 (.A(n564),
	.B(n58),
	.C(n569),
	.D(n592),
	.Y(n459));
   OAI22X1 U427 (.A(n564),
	.B(n59),
	.C(n579),
	.D(n592),
	.Y(n458));
   OAI22X1 U428 (.A(n564),
	.B(n60),
	.C(n581),
	.D(n592),
	.Y(n457));
   OAI22X1 U429 (.A(n564),
	.B(n61),
	.C(n571),
	.D(n592),
	.Y(n456));
   OAI22X1 U430 (.A(n564),
	.B(n62),
	.C(n573),
	.D(n592),
	.Y(n455));
   OAI22X1 U431 (.A(n91),
	.B(n63),
	.C(n569),
	.D(n353),
	.Y(n454));
   AOI22X1 U432 (.A(n353),
	.B(dp_n17),
	.C(memdata[4]),
	.D(n91),
	.Y(n354));
   AOI22X1 U433 (.A(n353),
	.B(dp_n16),
	.C(memdata[5]),
	.D(n91),
	.Y(n355));
   NAND2X1 U434 (.A(n205),
	.B(n93),
	.Y(n353));
   AOI22X1 U435 (.A(memdata[0]),
	.B(n86),
	.C(n357),
	.D(dp_n15),
	.Y(n356));
   OAI22X1 U436 (.A(n565),
	.B(n357),
	.C(n86),
	.D(n67),
	.Y(n450));
   OAI22X1 U437 (.A(n567),
	.B(n357),
	.C(n86),
	.D(n69),
	.Y(n449));
   OAI22X1 U438 (.A(n581),
	.B(n357),
	.C(n86),
	.D(n587),
	.Y(n448));
   OAI22X1 U439 (.A(n571),
	.B(n357),
	.C(n86),
	.D(n71),
	.Y(n447));
   OAI22X1 U440 (.A(n573),
	.B(n357),
	.C(n86),
	.D(n73),
	.Y(n446));
   NAND2X1 U441 (.A(n358),
	.B(n96),
	.Y(n357));
   NAND2X1 U442 (.A(n360),
	.B(n346),
	.Y(memread));
   NAND2X1 U443 (.A(n180),
	.B(n95),
	.Y(n346));
   OAI21X1 U444 (.A(n590),
	.B(n361),
	.C(n362),
	.Y(dp_rd2[7]));
   OAI21X1 U445 (.A(n363),
	.B(n364),
	.C(n590),
	.Y(n362));
   OAI22X1 U446 (.A(n106),
	.B(FE_OFN3_n365),
	.C(n104),
	.D(FE_OFN4_n366),
	.Y(n364));
   OAI22X1 U447 (.A(n102),
	.B(n597),
	.C(n100),
	.D(n598),
	.Y(n363));
   AOI21X1 U448 (.A(n596),
	.B(dp_rf_REGS[15]),
	.C(n369),
	.Y(n361));
   OAI22X1 U449 (.A(n103),
	.B(n597),
	.C(n101),
	.D(n598),
	.Y(n369));
   OAI21X1 U450 (.A(dp_n15),
	.B(n370),
	.C(n371),
	.Y(dp_rd2[6]));
   OAI21X1 U451 (.A(n372),
	.B(n373),
	.C(dp_n15),
	.Y(n371));
   OAI22X1 U452 (.A(n169),
	.B(FE_OFN3_n365),
	.C(n167),
	.D(FE_OFN4_n366),
	.Y(n373));
   OAI22X1 U453 (.A(n165),
	.B(n597),
	.C(n163),
	.D(n598),
	.Y(n372));
   AOI21X1 U454 (.A(n596),
	.B(dp_rf_REGS[14]),
	.C(n374),
	.Y(n370));
   OAI22X1 U455 (.A(n166),
	.B(n597),
	.C(n164),
	.D(n598),
	.Y(n374));
   OAI21X1 U456 (.A(n590),
	.B(n375),
	.C(n376),
	.Y(dp_rd2[5]));
   OAI21X1 U457 (.A(n377),
	.B(n378),
	.C(n590),
	.Y(n376));
   OAI22X1 U458 (.A(n160),
	.B(FE_OFN3_n365),
	.C(n158),
	.D(FE_OFN4_n366),
	.Y(n378));
   OAI22X1 U459 (.A(n156),
	.B(n597),
	.C(n154),
	.D(n598),
	.Y(n377));
   AOI21X1 U460 (.A(n596),
	.B(dp_rf_REGS[13]),
	.C(n379),
	.Y(n375));
   OAI22X1 U461 (.A(n157),
	.B(n597),
	.C(n155),
	.D(n598),
	.Y(n379));
   OAI21X1 U462 (.A(dp_n15),
	.B(n380),
	.C(n381),
	.Y(dp_rd2[4]));
   OAI21X1 U463 (.A(n382),
	.B(n383),
	.C(n590),
	.Y(n381));
   OAI22X1 U464 (.A(n151),
	.B(FE_OFN3_n365),
	.C(n149),
	.D(FE_OFN4_n366),
	.Y(n383));
   OAI22X1 U465 (.A(n147),
	.B(n597),
	.C(n145),
	.D(n598),
	.Y(n382));
   AOI21X1 U466 (.A(n596),
	.B(dp_rf_REGS[12]),
	.C(n384),
	.Y(n380));
   OAI22X1 U467 (.A(n148),
	.B(n597),
	.C(n146),
	.D(n598),
	.Y(n384));
   OAI21X1 U468 (.A(n590),
	.B(n385),
	.C(n386),
	.Y(dp_rd2[3]));
   OAI21X1 U469 (.A(n387),
	.B(n388),
	.C(n590),
	.Y(n386));
   OAI22X1 U470 (.A(n142),
	.B(FE_OFN3_n365),
	.C(n140),
	.D(FE_OFN4_n366),
	.Y(n388));
   OAI22X1 U471 (.A(n138),
	.B(n597),
	.C(n136),
	.D(n598),
	.Y(n387));
   AOI21X1 U472 (.A(n596),
	.B(dp_rf_REGS[11]),
	.C(n389),
	.Y(n385));
   OAI22X1 U473 (.A(n139),
	.B(n597),
	.C(n137),
	.D(n598),
	.Y(n389));
   OAI21X1 U474 (.A(dp_n15),
	.B(n390),
	.C(n391),
	.Y(dp_rd2[2]));
   OAI21X1 U475 (.A(n392),
	.B(n393),
	.C(n590),
	.Y(n391));
   OAI22X1 U476 (.A(n133),
	.B(FE_OFN3_n365),
	.C(n131),
	.D(FE_OFN4_n366),
	.Y(n393));
   OAI22X1 U477 (.A(n129),
	.B(n597),
	.C(n127),
	.D(n598),
	.Y(n392));
   AOI21X1 U478 (.A(n596),
	.B(dp_rf_REGS[10]),
	.C(n394),
	.Y(n390));
   OAI22X1 U479 (.A(n130),
	.B(n597),
	.C(n128),
	.D(n598),
	.Y(n394));
   OAI21X1 U480 (.A(n590),
	.B(n395),
	.C(n396),
	.Y(dp_rd2[1]));
   OAI21X1 U481 (.A(n397),
	.B(n398),
	.C(n590),
	.Y(n396));
   OAI22X1 U482 (.A(n124),
	.B(FE_OFN3_n365),
	.C(n122),
	.D(FE_OFN4_n366),
	.Y(n398));
   OAI22X1 U483 (.A(n120),
	.B(n597),
	.C(n118),
	.D(n598),
	.Y(n397));
   AOI21X1 U484 (.A(n596),
	.B(dp_rf_REGS[9]),
	.C(n399),
	.Y(n395));
   OAI22X1 U485 (.A(n121),
	.B(n597),
	.C(n119),
	.D(n598),
	.Y(n399));
   OAI21X1 U486 (.A(dp_n15),
	.B(n400),
	.C(n401),
	.Y(dp_rd2[0]));
   OAI21X1 U487 (.A(n402),
	.B(n403),
	.C(n590),
	.Y(n401));
   OAI22X1 U488 (.A(n115),
	.B(FE_OFN3_n365),
	.C(n113),
	.D(FE_OFN4_n366),
	.Y(n403));
   NAND2X1 U489 (.A(n69),
	.B(n67),
	.Y(n365));
   OAI22X1 U490 (.A(n111),
	.B(n597),
	.C(n109),
	.D(n598),
	.Y(n402));
   AOI21X1 U491 (.A(n596),
	.B(dp_rf_REGS[8]),
	.C(n404),
	.Y(n400));
   OAI22X1 U492 (.A(n112),
	.B(n597),
	.C(n110),
	.D(n598),
	.Y(n404));
   NAND2X1 U495 (.A(dp_n14),
	.B(n69),
	.Y(n366));
   OAI21X1 U496 (.A(dp_n12),
	.B(n405),
	.C(n406),
	.Y(dp_rd1[7]));
   OAI21X1 U497 (.A(n407),
	.B(n408),
	.C(dp_n12),
	.Y(n406));
   OAI22X1 U498 (.A(n106),
	.B(FE_OFN5_n409),
	.C(n104),
	.D(FE_OFN6_n410),
	.Y(n408));
   OAI22X1 U499 (.A(n102),
	.B(n594),
	.C(n100),
	.D(n595),
	.Y(n407));
   AOI21X1 U500 (.A(n593),
	.B(dp_rf_REGS[15]),
	.C(n413),
	.Y(n405));
   OAI22X1 U501 (.A(n103),
	.B(n594),
	.C(n101),
	.D(n595),
	.Y(n413));
   OAI21X1 U502 (.A(n588),
	.B(n414),
	.C(n415),
	.Y(dp_rd1[6]));
   OAI21X1 U503 (.A(n416),
	.B(n417),
	.C(n588),
	.Y(n415));
   OAI22X1 U504 (.A(n169),
	.B(FE_OFN5_n409),
	.C(n167),
	.D(FE_OFN6_n410),
	.Y(n417));
   OAI22X1 U505 (.A(n165),
	.B(n594),
	.C(n163),
	.D(n595),
	.Y(n416));
   AOI21X1 U506 (.A(n593),
	.B(dp_rf_REGS[14]),
	.C(n418),
	.Y(n414));
   OAI22X1 U507 (.A(n166),
	.B(n594),
	.C(n164),
	.D(n595),
	.Y(n418));
   OAI21X1 U508 (.A(dp_n12),
	.B(n419),
	.C(n420),
	.Y(dp_rd1[5]));
   OAI21X1 U509 (.A(n421),
	.B(n422),
	.C(n588),
	.Y(n420));
   OAI22X1 U510 (.A(n160),
	.B(FE_OFN5_n409),
	.C(n158),
	.D(FE_OFN6_n410),
	.Y(n422));
   OAI22X1 U511 (.A(n156),
	.B(n594),
	.C(n154),
	.D(n595),
	.Y(n421));
   AOI21X1 U512 (.A(n593),
	.B(dp_rf_REGS[13]),
	.C(n423),
	.Y(n419));
   OAI22X1 U513 (.A(n157),
	.B(n594),
	.C(n155),
	.D(n595),
	.Y(n423));
   OAI21X1 U514 (.A(n588),
	.B(n424),
	.C(n425),
	.Y(dp_rd1[4]));
   OAI21X1 U515 (.A(n426),
	.B(n427),
	.C(n588),
	.Y(n425));
   OAI22X1 U516 (.A(n151),
	.B(FE_OFN5_n409),
	.C(n149),
	.D(FE_OFN6_n410),
	.Y(n427));
   OAI22X1 U517 (.A(n147),
	.B(n594),
	.C(n145),
	.D(n595),
	.Y(n426));
   AOI21X1 U518 (.A(n593),
	.B(dp_rf_REGS[12]),
	.C(n428),
	.Y(n424));
   OAI22X1 U519 (.A(n148),
	.B(n594),
	.C(n146),
	.D(n595),
	.Y(n428));
   OAI21X1 U520 (.A(dp_n12),
	.B(n429),
	.C(n430),
	.Y(dp_rd1[3]));
   OAI21X1 U521 (.A(n431),
	.B(n432),
	.C(n588),
	.Y(n430));
   OAI22X1 U522 (.A(n142),
	.B(FE_OFN5_n409),
	.C(n140),
	.D(FE_OFN6_n410),
	.Y(n432));
   OAI22X1 U523 (.A(n138),
	.B(n594),
	.C(n136),
	.D(n595),
	.Y(n431));
   AOI21X1 U524 (.A(n593),
	.B(dp_rf_REGS[11]),
	.C(n433),
	.Y(n429));
   OAI22X1 U525 (.A(n139),
	.B(n594),
	.C(n137),
	.D(n595),
	.Y(n433));
   OAI21X1 U526 (.A(n588),
	.B(n434),
	.C(n435),
	.Y(dp_rd1[2]));
   OAI21X1 U527 (.A(n436),
	.B(n437),
	.C(n588),
	.Y(n435));
   OAI22X1 U528 (.A(n133),
	.B(FE_OFN5_n409),
	.C(n131),
	.D(FE_OFN6_n410),
	.Y(n437));
   OAI22X1 U529 (.A(n129),
	.B(n594),
	.C(n127),
	.D(n595),
	.Y(n436));
   AOI21X1 U530 (.A(n593),
	.B(dp_rf_REGS[10]),
	.C(n438),
	.Y(n434));
   OAI22X1 U531 (.A(n130),
	.B(n594),
	.C(n128),
	.D(n595),
	.Y(n438));
   OAI21X1 U532 (.A(dp_n12),
	.B(n439),
	.C(n440),
	.Y(dp_rd1[1]));
   OAI21X1 U533 (.A(n441),
	.B(n442),
	.C(n588),
	.Y(n440));
   OAI22X1 U534 (.A(n124),
	.B(FE_OFN5_n409),
	.C(n122),
	.D(FE_OFN6_n410),
	.Y(n442));
   OAI22X1 U535 (.A(n120),
	.B(n594),
	.C(n118),
	.D(n595),
	.Y(n441));
   AOI21X1 U536 (.A(n593),
	.B(dp_rf_REGS[9]),
	.C(n443),
	.Y(n439));
   OAI22X1 U537 (.A(n121),
	.B(n594),
	.C(n119),
	.D(n595),
	.Y(n443));
   OAI21X1 U538 (.A(n588),
	.B(n444),
	.C(n445),
	.Y(dp_rd1[0]));
   OAI21X1 U539 (.A(n451),
	.B(n452),
	.C(n588),
	.Y(n445));
   OAI22X1 U540 (.A(n115),
	.B(FE_OFN5_n409),
	.C(n113),
	.D(FE_OFN6_n410),
	.Y(n452));
   NAND2X1 U541 (.A(n73),
	.B(n71),
	.Y(n409));
   OAI22X1 U542 (.A(n111),
	.B(n594),
	.C(n109),
	.D(n595),
	.Y(n451));
   AOI21X1 U543 (.A(n593),
	.B(dp_rf_REGS[8]),
	.C(n453),
	.Y(n444));
   OAI22X1 U544 (.A(n112),
	.B(n594),
	.C(n110),
	.D(n595),
	.Y(n453));
   NAND2X1 U547 (.A(dp_n11),
	.B(n73),
	.Y(n410));
   OR2X1 U548 (.A(n467),
	.B(n541),
	.Y(cont_nextstate[3]));
   OAI21X1 U549 (.A(n1),
	.B(n351),
	.C(n2),
	.Y(n541));
   OAI21X1 U550 (.A(cont_state[1]),
	.B(n344),
	.C(n543),
	.Y(n467));
   NAND3X1 U551 (.A(n54),
	.B(n48),
	.C(n49),
	.Y(n543));
   NAND2X1 U552 (.A(cont_state[3]),
	.B(n358),
	.Y(n344));
   NAND3X1 U553 (.A(n592),
	.B(n545),
	.C(n546),
	.Y(cont_nextstate[2]));
   AOI21X1 U554 (.A(n547),
	.B(n548),
	.C(n549),
	.Y(n546));
   NOR2X1 U555 (.A(instr[31]),
	.B(instr[30]),
	.Y(n548));
   NOR2X1 U556 (.A(n51),
	.B(n544),
	.Y(n547));
   NAND3X1 U558 (.A(n550),
	.B(n545),
	.C(n551),
	.Y(cont_nextstate[1]));
   AOI22X1 U559 (.A(n358),
	.B(n97),
	.C(n205),
	.D(n98),
	.Y(n551));
   NOR2X1 U560 (.A(n98),
	.B(cont_state[2]),
	.Y(n358));
   OR2X1 U561 (.A(n542),
	.B(n351),
	.Y(n545));
   NAND3X1 U562 (.A(cont_state[0]),
	.B(n96),
	.C(cont_state[2]),
	.Y(n351));
   NAND2X1 U563 (.A(n97),
	.B(n180),
	.Y(n347));
   NAND3X1 U564 (.A(n349),
	.B(n53),
	.C(instr[31]),
	.Y(n542));
   OR2X1 U565 (.A(n549),
	.B(n552),
	.Y(cont_nextstate[0]));
   OAI21X1 U566 (.A(cont_state[3]),
	.B(n553),
	.C(n2),
	.Y(n552));
   OAI21X1 U567 (.A(n87),
	.B(n555),
	.C(n550),
	.Y(n554));
   NAND3X1 U568 (.A(instr[28]),
	.B(n556),
	.C(n557),
	.Y(n550));
   NOR2X1 U569 (.A(n558),
	.B(n559),
	.Y(n557));
   NAND2X1 U570 (.A(n53),
	.B(n48),
	.Y(n559));
   NAND2X1 U571 (.A(n349),
	.B(n48),
	.Y(n555));
   NOR2X1 U572 (.A(n558),
	.B(instr[28]),
	.Y(n349));
   NAND3X1 U573 (.A(n51),
	.B(n54),
	.C(n50),
	.Y(n558));
   OAI21X1 U574 (.A(n544),
	.B(n560),
	.C(n360),
	.Y(n549));
   NAND2X1 U575 (.A(instr[31]),
	.B(n51),
	.Y(n560));
   NAND3X1 U576 (.A(n556),
	.B(n50),
	.C(n561),
	.Y(n544));
   NOR2X1 U577 (.A(instr[29]),
	.B(instr[28]),
	.Y(n561));
   NOR2X1 U578 (.A(n235),
	.B(cont_state[3]),
	.Y(n556));
   NAND3X1 U579 (.A(n98),
	.B(n97),
	.C(cont_state[2]),
	.Y(n235));
   OAI22X1 U580 (.A(n591),
	.B(n99),
	.C(n170),
	.D(FE_OFN7_n562),
	.Y(adr[7]));
   OAI22X1 U581 (.A(n591),
	.B(n162),
	.C(n161),
	.D(FE_OFN7_n562),
	.Y(adr[6]));
   OAI22X1 U582 (.A(n591),
	.B(n153),
	.C(n152),
	.D(FE_OFN7_n562),
	.Y(adr[5]));
   OAI22X1 U583 (.A(n591),
	.B(n144),
	.C(n143),
	.D(FE_OFN7_n562),
	.Y(adr[4]));
   OAI22X1 U584 (.A(n591),
	.B(n135),
	.C(n134),
	.D(FE_OFN7_n562),
	.Y(adr[3]));
   OAI22X1 U585 (.A(n591),
	.B(n126),
	.C(n125),
	.D(FE_OFN7_n562),
	.Y(adr[2]));
   OAI22X1 U586 (.A(n591),
	.B(n117),
	.C(n116),
	.D(FE_OFN7_n562),
	.Y(adr[1]));
   OAI22X1 U587 (.A(n591),
	.B(n108),
	.C(n107),
	.D(FE_OFN7_n562),
	.Y(adr[0]));
   NAND2X1 U588 (.A(n359),
	.B(n360),
	.Y(n562));
   NAND3X1 U589 (.A(cont_state[2]),
	.B(n98),
	.C(n205),
	.Y(n360));
   NOR2X1 U590 (.A(n97),
	.B(cont_state[3]),
	.Y(n205));
   NAND3X1 U591 (.A(n93),
	.B(n97),
	.C(cont_state[3]),
	.Y(n359));
   NAND2X1 U592 (.A(n95),
	.B(n98),
	.Y(n553));
   DFFPOSX1_SCAN dp_ir0_q_reg_7_ (.D(n468),
	.TI(instr[30]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[31]));
   DFFPOSX1_SCAN dp_ir0_q_reg_2_ (.D(n563),
	.TI(dp_a[7]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[26]));
   DFFPOSX1_SCAN dp_ir0_q_reg_3_ (.D(n466),
	.TI(instr[26]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[27]));
   DFFPOSX1_SCAN dp_ir0_q_reg_4_ (.D(n465),
	.TI(instr[27]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[28]));
   DFFPOSX1_SCAN dp_ir0_q_reg_5_ (.D(n464),
	.TI(instr[28]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[29]));
   DFFPOSX1_SCAN dp_ir0_q_reg_6_ (.D(n463),
	.TI(instr[29]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[30]));
   DFFPOSX1_SCAN dp_ir3_q_reg_0_ (.D(n462),
	.TI(dp_n16),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[0]));
   DFFPOSX1_SCAN dp_ir3_q_reg_1_ (.D(n461),
	.TI(instr[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[1]));
   DFFPOSX1_SCAN dp_ir3_q_reg_2_ (.D(n460),
	.TI(instr[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[2]));
   DFFPOSX1_SCAN dp_ir3_q_reg_3_ (.D(n459),
	.TI(instr[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[3]));
   DFFPOSX1_SCAN dp_ir3_q_reg_4_ (.D(n458),
	.TI(instr[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[4]));
   DFFPOSX1_SCAN dp_ir3_q_reg_5_ (.D(n457),
	.TI(instr[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(instr[5]));
   DFFPOSX1_SCAN dp_ir3_q_reg_6_ (.D(n456),
	.TI(instr[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n20));
   DFFPOSX1_SCAN dp_ir3_q_reg_7_ (.D(n455),
	.TI(dp_n20),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n19));
   DFFPOSX1_SCAN dp_ir2_q_reg_3_ (.D(n454),
	.TI(dp_n10),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n18));
   DFFPOSX1_SCAN dp_ir2_q_reg_4_ (.D(n64),
	.TI(dp_n18),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n17));
   DFFPOSX1_SCAN dp_ir2_q_reg_5_ (.D(n65),
	.TI(dp_n17),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n16));
   DFFPOSX1_SCAN dp_ir1_q_reg_0_ (.D(n66),
	.TI(instr[31]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n15));
   DFFPOSX1_SCAN dp_ir1_q_reg_1_ (.D(n450),
	.TI(dp_n15),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n14));
   DFFPOSX1_SCAN dp_ir1_q_reg_2_ (.D(n449),
	.TI(dp_n14),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n13));
   DFFPOSX1_SCAN dp_ir1_q_reg_5_ (.D(n448),
	.TI(dp_n13),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n12));
   DFFPOSX1_SCAN dp_ir1_q_reg_6_ (.D(n447),
	.TI(dp_n12),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n11));
   DFFPOSX1_SCAN dp_ir1_q_reg_7_ (.D(n446),
	.TI(dp_n11),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_n10));
   DFFPOSX1_SCAN dp_mdr_q_reg_0_ (.D(n578),
	.TI(dp_n19),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[0]));
   DFFPOSX1_SCAN dp_mdr_q_reg_1_ (.D(n566),
	.TI(dp_md[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[1]));
   DFFPOSX1_SCAN dp_mdr_q_reg_2_ (.D(n568),
	.TI(dp_md[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[2]));
   DFFPOSX1_SCAN dp_mdr_q_reg_3_ (.D(n570),
	.TI(dp_md[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[3]));
   DFFPOSX1_SCAN dp_mdr_q_reg_4_ (.D(n580),
	.TI(dp_md[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[4]));
   DFFPOSX1_SCAN dp_mdr_q_reg_5_ (.D(n582),
	.TI(dp_md[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[5]));
   DFFPOSX1_SCAN dp_mdr_q_reg_6_ (.D(n572),
	.TI(dp_md[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[6]));
   DFFPOSX1_SCAN dp_mdr_q_reg_7_ (.D(n574),
	.TI(dp_md[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_md[7]));
   DFFPOSX1_SCAN dp_areg_q_reg_7_ (.D(dp_rd1[7]),
	.TI(dp_a[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[7]));
   DFFPOSX1_SCAN dp_res_q_reg_7_ (.D(n540),
	.TI(dp_aluout[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[7]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__7_ (.D(n483),
	.TI(dp_rf_REGS[54]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[55]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__7_ (.D(n482),
	.TI(dp_rf_REGS[46]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[47]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__7_ (.D(n481),
	.TI(dp_rf_REGS[38]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[39]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__7_ (.D(n480),
	.TI(dp_rf_REGS[30]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[31]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__7_ (.D(n479),
	.TI(dp_rf_REGS[22]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[23]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__7_ (.D(n478),
	.TI(dp_rf_REGS[14]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[15]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__7_ (.D(n477),
	.TI(dp_rf_REGS[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[7]));
   DFFPOSX1_SCAN dp_wrd_q_reg_7_ (.D(dp_rd2[7]),
	.TI(writedata[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[7]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_0_ (.D(n476),
	.TI(dp_md[7]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[0]));
   DFFPOSX1_SCAN dp_res_q_reg_0_ (.D(n533),
	.TI(dp_pc[7]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[0]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__0_ (.D(n532),
	.TI(dp_rf_REGS[47]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[48]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__0_ (.D(n531),
	.TI(dp_rf_REGS[39]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[40]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__0_ (.D(n530),
	.TI(dp_rf_REGS[31]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[32]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__0_ (.D(n529),
	.TI(dp_rf_REGS[23]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[24]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__0_ (.D(n528),
	.TI(dp_rf_REGS[15]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[16]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__0_ (.D(n527),
	.TI(dp_rf_REGS[7]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[8]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__0_ (.D(n526),
	.TI(dp_aluout[7]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[0]));
   DFFPOSX1_SCAN dp_wrd_q_reg_0_ (.D(dp_rd2[0]),
	.TI(dp_rf_REGS[55]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[0]));
   DFFPOSX1_SCAN dp_areg_q_reg_0_ (.D(dp_rd1[0]),
	.TI(test_si),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[0]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_1_ (.D(n475),
	.TI(dp_pc[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[1]));
   DFFPOSX1_SCAN dp_res_q_reg_1_ (.D(n534),
	.TI(dp_aluout[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[1]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__1_ (.D(n525),
	.TI(dp_rf_REGS[48]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[49]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__1_ (.D(n524),
	.TI(dp_rf_REGS[40]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[41]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__1_ (.D(n523),
	.TI(dp_rf_REGS[32]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[33]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__1_ (.D(n522),
	.TI(dp_rf_REGS[24]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[25]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__1_ (.D(n521),
	.TI(dp_rf_REGS[16]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[17]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__1_ (.D(n520),
	.TI(dp_rf_REGS[8]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[9]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__1_ (.D(n519),
	.TI(dp_rf_REGS[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[1]));
   DFFPOSX1_SCAN dp_wrd_q_reg_1_ (.D(dp_rd2[1]),
	.TI(writedata[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[1]));
   DFFPOSX1_SCAN dp_areg_q_reg_1_ (.D(dp_rd1[1]),
	.TI(dp_a[0]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[1]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_2_ (.D(n474),
	.TI(dp_pc[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[2]));
   DFFPOSX1_SCAN dp_res_q_reg_2_ (.D(n535),
	.TI(dp_aluout[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[2]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__2_ (.D(n518),
	.TI(dp_rf_REGS[49]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[50]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__2_ (.D(n517),
	.TI(dp_rf_REGS[41]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[42]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__2_ (.D(n516),
	.TI(dp_rf_REGS[33]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[34]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__2_ (.D(n515),
	.TI(dp_rf_REGS[25]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[26]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__2_ (.D(n514),
	.TI(dp_rf_REGS[17]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[18]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__2_ (.D(n513),
	.TI(dp_rf_REGS[9]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[10]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__2_ (.D(n512),
	.TI(dp_rf_REGS[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[2]));
   DFFPOSX1_SCAN dp_wrd_q_reg_2_ (.D(dp_rd2[2]),
	.TI(writedata[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[2]));
   DFFPOSX1_SCAN dp_areg_q_reg_2_ (.D(dp_rd1[2]),
	.TI(dp_a[1]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[2]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_3_ (.D(n473),
	.TI(dp_pc[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[3]));
   DFFPOSX1_SCAN dp_res_q_reg_3_ (.D(n536),
	.TI(dp_aluout[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[3]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__3_ (.D(n511),
	.TI(dp_rf_REGS[50]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[51]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__3_ (.D(n510),
	.TI(dp_rf_REGS[42]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[43]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__3_ (.D(n509),
	.TI(dp_rf_REGS[34]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[35]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__3_ (.D(n508),
	.TI(dp_rf_REGS[26]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[27]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__3_ (.D(n507),
	.TI(dp_rf_REGS[18]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[19]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__3_ (.D(n506),
	.TI(dp_rf_REGS[10]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[11]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__3_ (.D(n505),
	.TI(dp_rf_REGS[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[3]));
   DFFPOSX1_SCAN dp_wrd_q_reg_3_ (.D(dp_rd2[3]),
	.TI(writedata[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[3]));
   DFFPOSX1_SCAN dp_areg_q_reg_3_ (.D(dp_rd1[3]),
	.TI(dp_a[2]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[3]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_4_ (.D(n472),
	.TI(dp_pc[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[4]));
   DFFPOSX1_SCAN dp_res_q_reg_4_ (.D(n537),
	.TI(dp_aluout[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[4]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__4_ (.D(n504),
	.TI(dp_rf_REGS[51]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[52]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__4_ (.D(n503),
	.TI(dp_rf_REGS[43]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[44]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__4_ (.D(n502),
	.TI(dp_rf_REGS[35]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[36]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__4_ (.D(n501),
	.TI(dp_rf_REGS[27]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[28]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__4_ (.D(n500),
	.TI(dp_rf_REGS[19]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[20]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__4_ (.D(n499),
	.TI(dp_rf_REGS[11]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[12]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__4_ (.D(n498),
	.TI(dp_rf_REGS[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[4]));
   DFFPOSX1_SCAN dp_wrd_q_reg_4_ (.D(dp_rd2[4]),
	.TI(writedata[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[4]));
   DFFPOSX1_SCAN dp_areg_q_reg_4_ (.D(dp_rd1[4]),
	.TI(dp_a[3]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[4]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_5_ (.D(n471),
	.TI(dp_pc[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[5]));
   DFFPOSX1_SCAN dp_res_q_reg_5_ (.D(n538),
	.TI(dp_aluout[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[5]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__5_ (.D(n497),
	.TI(dp_rf_REGS[52]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[53]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__5_ (.D(n496),
	.TI(dp_rf_REGS[44]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[45]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__5_ (.D(n495),
	.TI(dp_rf_REGS[36]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[37]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__5_ (.D(n494),
	.TI(dp_rf_REGS[28]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[29]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__5_ (.D(n493),
	.TI(dp_rf_REGS[20]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[21]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__5_ (.D(n492),
	.TI(dp_rf_REGS[12]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[13]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__5_ (.D(n491),
	.TI(dp_rf_REGS[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[5]));
   DFFPOSX1_SCAN dp_wrd_q_reg_5_ (.D(dp_rd2[5]),
	.TI(writedata[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[5]));
   DFFPOSX1_SCAN dp_areg_q_reg_5_ (.D(dp_rd1[5]),
	.TI(dp_a[4]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[5]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_6_ (.D(n470),
	.TI(dp_pc[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[6]));
   DFFPOSX1_SCAN dp_res_q_reg_6_ (.D(n539),
	.TI(dp_aluout[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_aluout[6]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_7__6_ (.D(n490),
	.TI(dp_rf_REGS[53]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[54]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_6__6_ (.D(n489),
	.TI(dp_rf_REGS[45]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[46]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_5__6_ (.D(n488),
	.TI(dp_rf_REGS[37]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[38]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_4__6_ (.D(n487),
	.TI(dp_rf_REGS[29]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[30]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_3__6_ (.D(n486),
	.TI(dp_rf_REGS[21]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[22]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_2__6_ (.D(n485),
	.TI(dp_rf_REGS[13]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[14]));
   DFFPOSX1_SCAN dp_rf_REGS_reg_1__6_ (.D(n484),
	.TI(dp_rf_REGS[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_rf_REGS[6]));
   DFFPOSX1_SCAN dp_wrd_q_reg_6_ (.D(dp_rd2[6]),
	.TI(writedata[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(writedata[6]));
   DFFPOSX1_SCAN dp_areg_q_reg_6_ (.D(dp_rd1[6]),
	.TI(dp_a[5]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_a[6]));
   DFFPOSX1_SCAN dp_pcreg_q_reg_7_ (.D(n469),
	.TI(dp_pc[6]),
	.TE(test_se),
	.CLK(clk),
	.Q(dp_pc[7]));
   AND2X2 U593 (.A(n205),
	.B(n358),
	.Y(n564));
   INVX2 U594 (.A(memdata[1]),
	.Y(n565));
   INVX2 U596 (.A(memdata[2]),
	.Y(n567));
   INVX2 U598 (.A(memdata[3]),
	.Y(n569));
   INVX2 U600 (.A(memdata[6]),
	.Y(n571));
   INVX2 U602 (.A(memdata[7]),
	.Y(n573));
   INVX2 U604 (.A(reset),
	.Y(n575));
   INVX2 U606 (.A(memdata[0]),
	.Y(n577));
   INVX2 U608 (.A(memdata[4]),
	.Y(n579));
   INVX2 U610 (.A(memdata[5]),
	.Y(n581));
   INVX2 U612 (.A(FE_OFN12_n187),
	.Y(n602));
   INVX2 U613 (.A(FE_OFN8_n183),
	.Y(n606));
   INVX2 U614 (.A(n245),
	.Y(n35));
   INVX2 U615 (.A(FE_OFN10_n185),
	.Y(n604));
   INVX2 U616 (.A(FE_OFN9_n184),
	.Y(n605));
   INVX2 U617 (.A(FE_OFN14_n189),
	.Y(n600));
   INVX2 U618 (.A(FE_OFN13_n188),
	.Y(n601));
   INVX2 U619 (.A(FE_OFN11_n186),
	.Y(n603));
   INVX2 U620 (.A(FE_OFN7_n562),
	.Y(n591));
   INVX2 U621 (.A(n589),
	.Y(n590));
   INVX2 U622 (.A(n564),
	.Y(n592));
   INVX4 U623 (.A(n584),
	.Y(n598));
   INVX4 U624 (.A(n586),
	.Y(n595));
   INVX2 U625 (.A(n583),
	.Y(n597));
   INVX4 U626 (.A(n585),
	.Y(n594));
   INVX2 U627 (.A(n587),
	.Y(n588));
   INVX2 U628 (.A(dp_n15),
	.Y(n589));
   INVX2 U629 (.A(FE_OFN0_n190),
	.Y(n599));
   INVX2 U630 (.A(FE_OFN4_n366),
	.Y(n596));
   AND2X2 U631 (.A(dp_n13),
	.B(n67),
	.Y(n583));
   AND2X2 U632 (.A(dp_n13),
	.B(dp_n14),
	.Y(n584));
   INVX2 U633 (.A(FE_OFN6_n410),
	.Y(n593));
   AND2X2 U634 (.A(dp_n10),
	.B(n71),
	.Y(n585));
   AND2X2 U635 (.A(dp_n10),
	.B(dp_n11),
	.Y(n586));
   INVX2 U636 (.A(dp_n12),
	.Y(n587));
endmodule

