###################################################################

# Created by write_sdc on Thu Apr 23 17:40:05 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
set_max_area 0
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[7]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[6]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[5]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[4]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[3]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[2]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[1]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {a[0]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[7]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[6]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[5]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[4]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[3]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[2]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[1]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports {b[0]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports            \
{alucont[2]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports            \
{alucont[1]}]
set_driving_cell -lib_cell INVX1 -library osu05_stdcells [get_ports            \
{alucont[0]}]
set_fanout_load 8 [get_ports {result[7]}]
set_fanout_load 8 [get_ports {result[6]}]
set_fanout_load 8 [get_ports {result[5]}]
set_fanout_load 8 [get_ports {result[4]}]
set_fanout_load 8 [get_ports {result[3]}]
set_fanout_load 8 [get_ports {result[2]}]
set_fanout_load 8 [get_ports {result[1]}]
set_fanout_load 8 [get_ports {result[0]}]
set_load -pin_load 0.1 [get_ports {result[7]}]
set_load -pin_load 0.1 [get_ports {result[6]}]
set_load -pin_load 0.1 [get_ports {result[5]}]
set_load -pin_load 0.1 [get_ports {result[4]}]
set_load -pin_load 0.1 [get_ports {result[3]}]
set_load -pin_load 0.1 [get_ports {result[2]}]
set_load -pin_load 0.1 [get_ports {result[1]}]
set_load -pin_load 0.1 [get_ports {result[0]}]
set_max_fanout 1 [get_ports {a[7]}]
set_max_fanout 1 [get_ports {a[6]}]
set_max_fanout 1 [get_ports {a[5]}]
set_max_fanout 1 [get_ports {a[4]}]
set_max_fanout 1 [get_ports {a[3]}]
set_max_fanout 1 [get_ports {a[2]}]
set_max_fanout 1 [get_ports {a[1]}]
set_max_fanout 1 [get_ports {a[0]}]
set_max_fanout 1 [get_ports {b[7]}]
set_max_fanout 1 [get_ports {b[6]}]
set_max_fanout 1 [get_ports {b[5]}]
set_max_fanout 1 [get_ports {b[4]}]
set_max_fanout 1 [get_ports {b[3]}]
set_max_fanout 1 [get_ports {b[2]}]
set_max_fanout 1 [get_ports {b[1]}]
set_max_fanout 1 [get_ports {b[0]}]
set_max_fanout 1 [get_ports {alucont[2]}]
set_max_fanout 1 [get_ports {alucont[1]}]
set_max_fanout 1 [get_ports {alucont[0]}]
create_clock -name clk  -period 10  -waveform {0 5}
set_clock_latency 0.3  [get_clocks clk]
set_input_delay -clock clk  2  [get_ports {a[7]}]
set_input_delay -clock clk  2  [get_ports {a[6]}]
set_input_delay -clock clk  2  [get_ports {a[5]}]
set_input_delay -clock clk  2  [get_ports {a[4]}]
set_input_delay -clock clk  2  [get_ports {a[3]}]
set_input_delay -clock clk  2  [get_ports {a[2]}]
set_input_delay -clock clk  2  [get_ports {a[1]}]
set_input_delay -clock clk  2  [get_ports {a[0]}]
set_input_delay -clock clk  2  [get_ports {b[7]}]
set_input_delay -clock clk  2  [get_ports {b[6]}]
set_input_delay -clock clk  2  [get_ports {b[5]}]
set_input_delay -clock clk  2  [get_ports {b[4]}]
set_input_delay -clock clk  2  [get_ports {b[3]}]
set_input_delay -clock clk  2  [get_ports {b[2]}]
set_input_delay -clock clk  2  [get_ports {b[1]}]
set_input_delay -clock clk  2  [get_ports {b[0]}]
set_input_delay -clock clk  2  [get_ports {alucont[2]}]
set_input_delay -clock clk  2  [get_ports {alucont[1]}]
set_input_delay -clock clk  2  [get_ports {alucont[0]}]
set_output_delay -clock clk  1.65  [get_ports {result[7]}]
set_output_delay -clock clk  1.65  [get_ports {result[6]}]
set_output_delay -clock clk  1.65  [get_ports {result[5]}]
set_output_delay -clock clk  1.65  [get_ports {result[4]}]
set_output_delay -clock clk  1.65  [get_ports {result[3]}]
set_output_delay -clock clk  1.65  [get_ports {result[2]}]
set_output_delay -clock clk  1.65  [get_ports {result[1]}]
set_output_delay -clock clk  1.65  [get_ports {result[0]}]
